version: "3"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub
    networks:
      - appium
    ports:
      - 5555:4444

# 不推荐使用 连接物理机很麻烦
  # real_device:
  #   image: budtmo/docker-android-real-device
  #   networks:
  #     - appium
  #   privileged: true
  #   depends_on:
  #     - selenium_hub
  #   ports:
  #     - 6080
  #   volumes:
  #     - ./video-real-device:/tmp/video
  #     - /dev/bus/usb:/dev/bus/usb
  #     - ~/.android:/root/.android
  #   environment:
  #     - CONNECT_TO_GRID=true
  #     - APPIUM=true
  #     - SELENIUM_HOST=selenium_hub
  #     - AUTO_RECORD=true
  #     - BROWSER_NAME=chrome

  # Using Appium Docker Android  
  real_device:
    image: appium/appium
    depends_on:
      - selenium_hub
    networks:
      - appium
    privileged: true
    ports:
      - 4723
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - ./:/root/tmp
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - ANDROID_DEVICES=172.16.16.67:5555,172.16.10.40:5555
      - REMOTE_ADB=true

  # Docker-Android for Android application testing
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    privileged: true
    # Increase scale number if needed
    networks:
      - appium
    depends_on:
      - selenium_hub
      - real_device
    ports:
      - 6080
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - ./:/root/tmp
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true

  # Docker-Android for mobile website testing with chrome browser
  # Chrome browser exists only for version 7.0 and 7.1.1
  samsung_galaxy_web_7.1.1:
    image: budtmo/docker-android-x86-8.1
    networks:
      - appium    
    privileged: true
    # Increase scale number if needed

    depends_on: 
      - selenium_hub
      - real_device
    ports:
      - 6080
    volumes:
      - ./:/root/tmp
      - ./video-samsung_7.1.1:/tmp/video
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=true
      - AUTO_RECORD=true

  # # Docker-Android for mobile website testing with default browser
  # # Default browser exists only for version 5.0.1, 5.1.1 and 6.0
  # samsung_galaxy_web_5.1.1:
  #   image: budtmo/docker-android-x86-5.1.1
  #   privileged: true
  #   # Increase scale number if needed

  #   depends_on:
  #     - selenium_hub
  #     - real_device
  #   ports:
  #     - 6080
  #   volumes:
  #     - ./:/root/tmp
  #     - ./video-samsung_5.1.1:/tmp/video
  #   environment:
  #     - DEVICE=Samsung Galaxy S6
  #     - CONNECT_TO_GRID=true
  #     - APPIUM=true
  #     - SELENIUM_HOST=selenium_hub
  #     - MOBILE_WEB_TEST=true
  #     - AUTO_RECORD=true

networks:
  appium:
    driver: bridge